"""sync_models_fix_users_table

Revision ID: 87e7271aed8b
Revises: f9a075ca46e9
Create Date: 2025-12-16 11:33:55.443373

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '87e7271aed8b'
down_revision = 'f9a075ca46e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ix_memotion_user_email'), table_name='user', schema='memotion')
    # op.drop_index(op.f('ix_memotion_user_full_name'), table_name='user', schema='memotion')
    # op.drop_table('user', schema='memotion')
    # op.drop_table('patient_mental_decline')
    # op.drop_index(op.f('ix_user_email'), table_name='user')
    # op.drop_index(op.f('ix_user_full_name'), table_name='user')
    # op.drop_table('user')
    # op.drop_table('patient_caretaker')
    # op.drop_table('task')
    # op.drop_table('nutrition_library')
    # op.drop_table('task_reminder')
    # op.drop_table('patient_loneliness')
    # op.drop_table('medication_library')
    # op.drop_table('users')
    # op.drop_table('exercise_library')
    # op.drop_table('notification')
    # op.drop_table('care_plan')
    # op.drop_table('health_daily_track')
    # op.drop_table('patient_physical_therapy')
    # op.drop_table('patient_profile')
    # op.drop_constraint(op.f('health_daily_track_patient_id_track_date_key'), 'health_daily_track', schema='memotion', type_='unique')
    # op.create_unique_constraint('uq_patient_track_date', 'health_daily_track', ['patient_id', 'track_date'], schema='memotion')
    # op.add_column('patient_mental_decline', sa.Column('MMSE_score', sa.Integer(), nullable=True), schema='memotion')
    # op.drop_column('patient_mental_decline', 'mmse_score', schema='memotion')
    # op.add_column('patient_profile', sa.Column('BMI_score', sa.Integer(), nullable=True), schema='memotion')
    # op.add_column('patient_profile', sa.Column('MAP_score', sa.Integer(), nullable=True), schema='memotion')
    # op.add_column('patient_profile', sa.Column('RHR_score', sa.Integer(), nullable=True), schema='memotion')
    # op.add_column('patient_profile', sa.Column('ADL_score', sa.Integer(), nullable=True), schema='memotion')
    # op.add_column('patient_profile', sa.Column('IADL_score', sa.Integer(), nullable=True), schema='memotion')
    # op.drop_column('patient_profile', 'adl_score', schema='memotion')
    # op.drop_column('patient_profile', 'rhr_score', schema='memotion')
    # op.drop_column('patient_profile', 'iadl_score', schema='memotion')
    # op.drop_column('patient_profile', 'map_score', schema='memotion')
    # op.drop_column('patient_profile', 'bmi_score', schema='memotion')
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=False), schema='memotion')
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True), schema='memotion')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active', schema='memotion')
    op.drop_column('users', 'hashed_password', schema='memotion')
    op.add_column('patient_profile', sa.Column('bmi_score', sa.INTEGER(), autoincrement=False, nullable=True), schema='memotion')
    op.add_column('patient_profile', sa.Column('map_score', sa.INTEGER(), autoincrement=False, nullable=True), schema='memotion')
    op.add_column('patient_profile', sa.Column('iadl_score', sa.INTEGER(), autoincrement=False, nullable=True), schema='memotion')
    op.add_column('patient_profile', sa.Column('rhr_score', sa.INTEGER(), autoincrement=False, nullable=True), schema='memotion')
    op.add_column('patient_profile', sa.Column('adl_score', sa.INTEGER(), autoincrement=False, nullable=True), schema='memotion')
    op.drop_column('patient_profile', 'IADL_score', schema='memotion')
    op.drop_column('patient_profile', 'ADL_score', schema='memotion')
    op.drop_column('patient_profile', 'RHR_score', schema='memotion')
    op.drop_column('patient_profile', 'MAP_score', schema='memotion')
    op.drop_column('patient_profile', 'BMI_score', schema='memotion')
    op.add_column('patient_mental_decline', sa.Column('mmse_score', sa.INTEGER(), autoincrement=False, nullable=True), schema='memotion')
    op.drop_column('patient_mental_decline', 'MMSE_score', schema='memotion')
    op.drop_constraint('uq_patient_track_date', 'health_daily_track', schema='memotion', type_='unique')
    op.create_unique_constraint(op.f('health_daily_track_patient_id_track_date_key'), 'health_daily_track', ['patient_id', 'track_date'], schema='memotion', postgresql_nulls_not_distinct=False)
    op.create_table('patient_profile',
    sa.Column('profile_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('bmi_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('map_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rhr_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('blood_glucose_level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('disease_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('condition_note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.CheckConstraint("disease_type::text = ANY (ARRAY['PHYSICAL_THERAPY'::character varying, 'MENTAL_DECLINE'::character varying, 'LONELINESS'::character varying]::text[])", name='patient_profile_disease_type_check'),
    sa.ForeignKeyConstraint(['patient_id'], ['users.user_id'], name='fk_profile_patient', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id', name='patient_profile_pkey'),
    sa.UniqueConstraint('patient_id', name='patient_profile_patient_id_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('patient_physical_therapy',
    sa.Column('profile_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('pain_location', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('pain_scale_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pain_character', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('previous_illness', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('previous_treatments', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('daily_function_note', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('doctor_recommended', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('doctor_treatment_plan', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['patient_profile.profile_id'], name=op.f('fk_pt_profile'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id', name=op.f('patient_physical_therapy_pkey'))
    )
    op.create_table('health_daily_track',
    sa.Column('track_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('track_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('heart_rate', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('blood_pressure', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('blood_sugar', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('mood_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_tasks', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('tasks_completed', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('medication_total', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('medication_taken', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('stress_level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('social_activity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('loneliness_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('voice_tone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.CheckConstraint('loneliness_score >= 0 AND loneliness_score <= 10', name=op.f('health_daily_track_loneliness_score_check')),
    sa.CheckConstraint('mood_score >= 1 AND mood_score <= 5', name=op.f('health_daily_track_mood_score_check')),
    sa.CheckConstraint('social_activity >= 0 AND social_activity <= 100', name=op.f('health_daily_track_social_activity_check')),
    sa.CheckConstraint('stress_level >= 0 AND stress_level <= 10', name=op.f('health_daily_track_stress_level_check')),
    sa.ForeignKeyConstraint(['patient_id'], ['users.user_id'], name=op.f('fk_health_track_patient'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('track_id', name=op.f('health_daily_track_pkey')),
    sa.UniqueConstraint('patient_id', 'track_date', name=op.f('health_daily_track_patient_id_track_date_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('care_plan',
    sa.Column('care_plan_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('caretaker_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['caretaker_id'], ['users.user_id'], name='fk_plan_caretaker', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['users.user_id'], name='fk_plan_patient', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('care_plan_id', name='care_plan_pkey'),
    sa.UniqueConstraint('patient_id', name='care_plan_patient_id_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('notification',
    sa.Column('notification_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('is_read', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint("type::text = ANY (ARRAY['REMINDER'::character varying, 'SYSTEM'::character varying, 'HEALTH'::character varying, 'TASK'::character varying]::text[])", name=op.f('notification_type_check')),
    sa.ForeignKeyConstraint(['task_id'], ['task.task_id'], name=op.f('notification_task_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('notification_user_id_fkey')),
    sa.PrimaryKeyConstraint('notification_id', name=op.f('notification_pkey'))
    )
    op.create_table('exercise_library',
    sa.Column('exercise_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('target_body_region', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('difficulty_level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('video_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.CheckConstraint('difficulty_level >= 1 AND difficulty_level <= 5', name='exercise_library_difficulty_level_check'),
    sa.PrimaryKeyConstraint('exercise_id', name='exercise_library_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.CheckConstraint("role::text = ANY (ARRAY['PATIENT'::character varying, 'CARETAKER'::character varying]::text[])", name='users_role_check'),
    sa.PrimaryKeyConstraint('user_id', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('medication_library',
    sa.Column('medication_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('dosage', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('frequency_per_day', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('image_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('medication_id', name='medication_library_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('patient_loneliness',
    sa.Column('profile_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('previous_illness', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('daily_function_note', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('mood_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('behavior_change_note', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['patient_profile.profile_id'], name=op.f('fk_lonely_profile'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id', name=op.f('patient_loneliness_pkey'))
    )
    op.create_table('task_reminder',
    sa.Column('reminder_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('remind_before', postgresql.INTERVAL(), autoincrement=False, nullable=False),
    sa.Column('remind_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('channel', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'SCHEDULED'::character varying"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.CheckConstraint("channel::text = ANY (ARRAY['APP_NOTIFICATION'::character varying, 'SMS'::character varying, 'VOICE_CALL'::character varying]::text[])", name=op.f('task_reminder_channel_check')),
    sa.CheckConstraint("status::text = ANY (ARRAY['SCHEDULED'::character varying, 'SENT'::character varying, 'CANCELLED'::character varying]::text[])", name=op.f('task_reminder_status_check')),
    sa.ForeignKeyConstraint(['task_id'], ['task.task_id'], name=op.f('fk_reminder_task'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('reminder_id', name=op.f('task_reminder_pkey'))
    )
    op.create_table('nutrition_library',
    sa.Column('nutrition_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('calories', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('meal_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('image_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('nutrition_id', name='nutrition_library_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('task',
    sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('care_plan_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('owner_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('task_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('task_time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('task_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('medication_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('nutrition_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('exercise_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'PENDING'::character varying"), autoincrement=False, nullable=True),
    sa.Column('linked_task_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.CheckConstraint("owner_type::text = ANY (ARRAY['PATIENT'::character varying, 'CARETAKER'::character varying]::text[])", name=op.f('task_owner_type_check')),
    sa.CheckConstraint("status::text = ANY (ARRAY['PENDING'::character varying, 'DONE'::character varying, 'SKIPPED'::character varying]::text[])", name=op.f('task_status_check')),
    sa.CheckConstraint("task_type::text = ANY (ARRAY['MEDICATION'::character varying, 'NUTRITION'::character varying, 'EXERCISE'::character varying]::text[])", name=op.f('task_task_type_check')),
    sa.ForeignKeyConstraint(['care_plan_id'], ['care_plan.care_plan_id'], name=op.f('fk_task_plan'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise_library.exercise_id'], name=op.f('fk_task_exercise'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['linked_task_id'], ['task.task_id'], name=op.f('fk_link_task'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['medication_id'], ['medication_library.medication_id'], name=op.f('fk_task_medication'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['nutrition_id'], ['nutrition_library.nutrition_id'], name=op.f('fk_task_nutrition'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('task_id', name=op.f('task_pkey'))
    )
    op.create_table('patient_caretaker',
    sa.Column('patient_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('caretaker_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('assigned_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['caretaker_id'], ['users.user_id'], name=op.f('fk_caretaker'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['users.user_id'], name=op.f('fk_patient'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('patient_id', name=op.f('patient_caretaker_pkey')),
    sa.UniqueConstraint('caretaker_id', name=op.f('patient_caretaker_caretaker_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_login', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('user_pkey'))
    )
    op.create_index(op.f('ix_user_full_name'), 'user', ['full_name'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('patient_mental_decline',
    sa.Column('profile_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('mmse_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('previous_illness', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('fast_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('memory_issue_note', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('orientation_issue_note', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('mood_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('behavior_change_note', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('daily_function_note', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('stage_of_decline', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('doctor_recommended', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('doctor_treatment_plan', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['patient_profile.profile_id'], name=op.f('fk_md_profile'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id', name=op.f('patient_mental_decline_pkey'))
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_login', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('user_pkey')),
    schema='memotion'
    )
    op.create_index(op.f('ix_memotion_user_full_name'), 'user', ['full_name'], unique=False, schema='memotion')
    op.create_index(op.f('ix_memotion_user_email'), 'user', ['email'], unique=True, schema='memotion')
    # ### end Alembic commands ###
