"""add is_first_login to users

Revision ID: a736dd2e6470
Revises: b69fb50d5b5d
Create Date: 2026-01-17 18:53:06.664962

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a736dd2e6470'
down_revision = 'b69fb50d5b5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memotion_user_email'), table_name='user', schema='memotion')
    op.drop_index(op.f('ix_memotion_user_full_name'), table_name='user', schema='memotion')
    op.drop_table('user', schema='memotion')
    op.drop_table('task_reminder', schema='memotion')
    op.drop_table('health_daily_track', schema='memotion')
    op.drop_table('users', schema='memotion')
    op.drop_table('nutrition_library', schema='memotion')
    op.drop_table('care_plan', schema='memotion')
    op.drop_table('patient_loneliness', schema='memotion')
    op.drop_table('patient_mental_decline', schema='memotion')
    op.drop_table('medication_library', schema='memotion')
    op.drop_table('patient_physical_therapy', schema='memotion')
    op.drop_table('patient_profile', schema='memotion')
    op.drop_table('task', schema='memotion')
    op.drop_table('patient_caretaker', schema='memotion')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_full_name'), table_name='user')
    op.drop_table('user')
    op.drop_table('exercise_library', schema='memotion')
    op.drop_table('notification', schema='memotion')
    op.drop_constraint(op.f('fk_plan_caretaker'), 'care_plan', type_='foreignkey')
    op.drop_constraint(op.f('fk_plan_patient'), 'care_plan', type_='foreignkey')
    op.create_foreign_key(None, 'care_plan', 'users', ['caretaker_id'], ['user_id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'care_plan', 'users', ['patient_id'], ['user_id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('health_daily_track_patient_id_track_date_key'), 'health_daily_track', type_='unique')
    op.create_unique_constraint('uq_patient_track_date', 'health_daily_track', ['patient_id', 'track_date'], schema='public')
    op.drop_constraint(op.f('fk_health_track_patient'), 'health_daily_track', type_='foreignkey')
    op.create_foreign_key(None, 'health_daily_track', 'users', ['patient_id'], ['user_id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('notification_task_id_fkey'), 'notification', type_='foreignkey')
    op.drop_constraint(op.f('notification_user_id_fkey'), 'notification', type_='foreignkey')
    op.create_foreign_key(None, 'notification', 'users', ['user_id'], ['user_id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'notification', 'task', ['task_id'], ['task_id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('fk_caretaker'), 'patient_caretaker', type_='foreignkey')
    op.drop_constraint(op.f('fk_patient'), 'patient_caretaker', type_='foreignkey')
    op.create_foreign_key(None, 'patient_caretaker', 'users', ['patient_id'], ['user_id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'patient_caretaker', 'users', ['caretaker_id'], ['user_id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('fk_lonely_profile_new'), 'patient_loneliness', type_='foreignkey')
    op.create_foreign_key(None, 'patient_loneliness', 'patient_profile', ['profile_id'], ['profile_id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('fk_md_profile_new'), 'patient_mental_decline', type_='foreignkey')
    op.create_foreign_key(None, 'patient_mental_decline', 'patient_profile', ['profile_id'], ['profile_id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('fk_pt_profile_new'), 'patient_physical_therapy', type_='foreignkey')
    op.create_foreign_key(None, 'patient_physical_therapy', 'patient_profile', ['profile_id'], ['profile_id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('fk_profile_physical_therapy'), 'patient_profile', type_='foreignkey')
    op.drop_constraint(op.f('fk_profile_loneliness'), 'patient_profile', type_='foreignkey')
    op.drop_constraint(op.f('fk_profile_patient'), 'patient_profile', type_='foreignkey')
    op.create_foreign_key(None, 'patient_profile', 'users', ['patient_id'], ['user_id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.alter_column('task', 'task_duedate',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_constraint(op.f('fk_task_nutrition'), 'task', type_='foreignkey')
    op.drop_constraint(op.f('fk_link_task'), 'task', type_='foreignkey')
    op.drop_constraint(op.f('fk_task_exercise'), 'task', type_='foreignkey')
    op.drop_constraint(op.f('fk_task_medication'), 'task', type_='foreignkey')
    op.drop_constraint(op.f('fk_task_plan'), 'task', type_='foreignkey')
    op.create_foreign_key(None, 'task', 'nutrition_library', ['nutrition_id'], ['nutrition_id'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    op.create_foreign_key(None, 'task', 'care_plan', ['care_plan_id'], ['care_plan_id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'task', 'task', ['linked_task_id'], ['task_id'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    op.create_foreign_key(None, 'task', 'medication_library', ['medication_id'], ['medication_id'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    op.create_foreign_key(None, 'task', 'exercise_library', ['exercise_id'], ['exercise_id'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    op.drop_constraint(op.f('fk_reminder_task'), 'task_reminder', type_='foreignkey')
    op.create_foreign_key(None, 'task_reminder', 'task', ['task_id'], ['task_id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.add_column('users', sa.Column('is_first_login', sa.Boolean(), server_default=sa.text('true'), nullable=True))
    # Set existing users to True
    op.execute("UPDATE users SET is_first_login = true WHERE is_first_login IS NULL")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_first_login')
    op.drop_constraint(None, 'task_reminder', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_reminder_task'), 'task_reminder', 'task', ['task_id'], ['task_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'task', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'task', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'task', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'task', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'task', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_task_plan'), 'task', 'care_plan', ['care_plan_id'], ['care_plan_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_task_medication'), 'task', 'medication_library', ['medication_id'], ['medication_id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_task_exercise'), 'task', 'exercise_library', ['exercise_id'], ['exercise_id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_link_task'), 'task', 'task', ['linked_task_id'], ['task_id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_task_nutrition'), 'task', 'nutrition_library', ['nutrition_id'], ['nutrition_id'], ondelete='SET NULL')
    op.alter_column('task', 'task_duedate',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint(None, 'patient_profile', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_profile_patient'), 'patient_profile', 'users', ['patient_id'], ['user_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_profile_loneliness'), 'patient_profile', 'patient_loneliness', ['loneliness_id'], ['profile_id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_profile_physical_therapy'), 'patient_profile', 'patient_physical_therapy', ['physical_therapy_id'], ['profile_id'], ondelete='SET NULL')
    op.drop_constraint(None, 'patient_physical_therapy', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_pt_profile_new'), 'patient_physical_therapy', 'patient_profile', ['profile_id'], ['profile_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'patient_mental_decline', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_md_profile_new'), 'patient_mental_decline', 'patient_profile', ['profile_id'], ['profile_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'patient_loneliness', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_lonely_profile_new'), 'patient_loneliness', 'patient_profile', ['profile_id'], ['profile_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'patient_caretaker', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'patient_caretaker', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_patient'), 'patient_caretaker', 'users', ['patient_id'], ['user_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_caretaker'), 'patient_caretaker', 'users', ['caretaker_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'notification', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'notification', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('notification_user_id_fkey'), 'notification', 'users', ['user_id'], ['user_id'])
    op.create_foreign_key(op.f('notification_task_id_fkey'), 'notification', 'task', ['task_id'], ['task_id'])
    op.drop_constraint(None, 'health_daily_track', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_health_track_patient'), 'health_daily_track', 'users', ['patient_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint('uq_patient_track_date', 'health_daily_track', schema='public', type_='unique')
    op.create_unique_constraint(op.f('health_daily_track_patient_id_track_date_key'), 'health_daily_track', ['patient_id', 'track_date'])
    op.drop_constraint(None, 'care_plan', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'care_plan', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_plan_patient'), 'care_plan', 'users', ['patient_id'], ['user_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_plan_caretaker'), 'care_plan', 'users', ['caretaker_id'], ['user_id'], ondelete='CASCADE')
    op.create_table('notification',
    sa.Column('notification_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('task_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('is_read', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint("(type)::text = ANY ((ARRAY['REMINDER'::character varying, 'SYSTEM'::character varying, 'HEALTH'::character varying, 'TASK'::character varying])::text[])", name=op.f('notification_type_check')),
    sa.ForeignKeyConstraint(['task_id'], ['memotion.task.task_id'], name=op.f('notification_task_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['memotion.users.user_id'], name=op.f('notification_user_id_fkey')),
    sa.PrimaryKeyConstraint('notification_id', name=op.f('notification_pkey')),
    schema='memotion'
    )
    op.create_table('exercise_library',
    sa.Column('exercise_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('target_body_region', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('difficulty_level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('video_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.CheckConstraint('(difficulty_level >= 1) AND (difficulty_level <= 5)', name='exercise_library_difficulty_level_check'),
    sa.PrimaryKeyConstraint('exercise_id', name='exercise_library_pkey'),
    schema='memotion',
    postgresql_ignore_search_path=False
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_login', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('user_pkey'))
    )
    op.create_index(op.f('ix_user_full_name'), 'user', ['full_name'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('patient_caretaker',
    sa.Column('patient_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('caretaker_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('assigned_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['caretaker_id'], ['memotion.users.user_id'], name=op.f('fk_caretaker'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['memotion.users.user_id'], name=op.f('fk_patient'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('patient_id', name=op.f('patient_caretaker_pkey')),
    sa.UniqueConstraint('caretaker_id', name=op.f('patient_caretaker_caretaker_id_key')),
    schema='memotion'
    )
    op.create_table('task',
    sa.Column('task_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('care_plan_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('owner_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('task_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('task_time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('task_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('medication_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('nutrition_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('exercise_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'PENDING'::character varying"), autoincrement=False, nullable=True),
    sa.Column('linked_task_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.CheckConstraint("(owner_type)::text = ANY ((ARRAY['PATIENT'::character varying, 'CARETAKER'::character varying])::text[])", name='task_owner_type_check'),
    sa.CheckConstraint("(status)::text = ANY ((ARRAY['PENDING'::character varying, 'DONE'::character varying, 'SKIPPED'::character varying])::text[])", name='task_status_check'),
    sa.CheckConstraint("(task_type)::text = ANY ((ARRAY['MEDICATION'::character varying, 'NUTRITION'::character varying, 'EXERCISE'::character varying])::text[])", name='task_task_type_check'),
    sa.ForeignKeyConstraint(['care_plan_id'], ['memotion.care_plan.care_plan_id'], name='fk_task_plan', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exercise_id'], ['memotion.exercise_library.exercise_id'], name='fk_task_exercise', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['linked_task_id'], ['memotion.task.task_id'], name='fk_link_task', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['medication_id'], ['memotion.medication_library.medication_id'], name='fk_task_medication', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['nutrition_id'], ['memotion.nutrition_library.nutrition_id'], name='fk_task_nutrition', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('task_id', name='task_pkey'),
    schema='memotion',
    postgresql_ignore_search_path=False
    )
    op.create_table('patient_profile',
    sa.Column('profile_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('patient_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('gender', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('living_arrangement', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('bmi_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('map_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rhr_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('adl_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('iadl_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('blood_glucose_level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('disease_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('condition_note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('physical_therapy_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('mental_decline_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('loneliness_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.CheckConstraint("(disease_type)::text = ANY ((ARRAY['PHYSICAL_THERAPY'::character varying, 'MENTAL_DECLINE'::character varying, 'LONELINESS'::character varying])::text[])", name='patient_profile_disease_type_check'),
    sa.CheckConstraint("(gender)::text = ANY ((ARRAY['MALE'::character varying, 'FEMALE'::character varying])::text[])", name='patient_profile_gender_check'),
    sa.ForeignKeyConstraint(['patient_id'], ['memotion.users.user_id'], name='fk_profile_patient', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id', name='patient_profile_pkey'),
    sa.UniqueConstraint('patient_id', name='patient_profile_patient_id_key'),
    schema='memotion',
    postgresql_ignore_search_path=False
    )
    op.create_table('patient_physical_therapy',
    sa.Column('profile_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('pain_location', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('pain_scale_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pain_character', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('pain_assessment', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('muscle_tone', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('muscle_strength', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('balanced_valuation', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('fall_risk', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('self_stand_ability', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('tug_time', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('previous_illness', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('previous_treatments', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('daily_actities', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('doctor_recommended', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('doctor_treatment_plan', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.CheckConstraint("(self_stand_ability)::text = ANY ((ARRAY['EASY'::character varying, 'HARD'::character varying, 'IMPOSSIBLE'::character varying])::text[])", name=op.f('patient_physical_therapy_self_stand_ability_check')),
    sa.ForeignKeyConstraint(['profile_id'], ['memotion.patient_profile.profile_id'], name=op.f('fk_pt_profile'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id', name=op.f('patient_physical_therapy_pkey')),
    schema='memotion'
    )
    op.create_table('medication_library',
    sa.Column('medication_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('dosage', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('frequency_per_day', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('image_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('medication_id', name='medication_library_pkey'),
    schema='memotion',
    postgresql_ignore_search_path=False
    )
    op.create_table('patient_mental_decline',
    sa.Column('profile_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('mmse_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('previous_illness', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('previous_treatments', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('functional_assessment_staging_test_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('memory_issue', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('orientation_issue', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('community_affairs', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('home_relationship', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('daily_function_can_do', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('daily_function_need_help', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('behavior_change', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('doctor_recommended', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('doctor_treatment_plan', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['memotion.patient_profile.profile_id'], name=op.f('fk_md_profile'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id', name=op.f('patient_mental_decline_pkey')),
    schema='memotion'
    )
    op.create_table('patient_loneliness',
    sa.Column('profile_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('previous_illness', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('lsns6_family_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lsns6_friends_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ucla_loneliness_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gds15_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('mood_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('behavior_change_note', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['memotion.patient_profile.profile_id'], name=op.f('fk_lonely_profile'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id', name=op.f('patient_loneliness_pkey')),
    schema='memotion'
    )
    op.create_table('care_plan',
    sa.Column('care_plan_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('patient_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('caretaker_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['caretaker_id'], ['memotion.users.user_id'], name='fk_plan_caretaker', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['memotion.users.user_id'], name='fk_plan_patient', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('care_plan_id', name='care_plan_pkey'),
    sa.UniqueConstraint('patient_id', name='care_plan_patient_id_key'),
    schema='memotion',
    postgresql_ignore_search_path=False
    )
    op.create_table('nutrition_library',
    sa.Column('nutrition_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('calories', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('meal_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('image_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('nutrition_id', name='nutrition_library_pkey'),
    schema='memotion',
    postgresql_ignore_search_path=False
    )
    op.create_table('users',
    sa.Column('user_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.CheckConstraint("(role)::text = ANY ((ARRAY['PATIENT'::character varying, 'CARETAKER'::character varying])::text[])", name='users_role_check'),
    sa.PrimaryKeyConstraint('user_id', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_key'),
    schema='memotion',
    postgresql_ignore_search_path=False
    )
    op.create_table('health_daily_track',
    sa.Column('track_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('patient_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('track_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('heart_rate', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('blood_pressure', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('blood_sugar', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('mood_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_tasks', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('tasks_completed', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('medication_total', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('medication_taken', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('stress_level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('social_activity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('loneliness_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('voice_tone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.CheckConstraint('(loneliness_score >= 0) AND (loneliness_score <= 10)', name=op.f('health_daily_track_loneliness_score_check')),
    sa.CheckConstraint('(mood_score >= 1) AND (mood_score <= 5)', name=op.f('health_daily_track_mood_score_check')),
    sa.CheckConstraint('(social_activity >= 0) AND (social_activity <= 100)', name=op.f('health_daily_track_social_activity_check')),
    sa.CheckConstraint('(stress_level >= 0) AND (stress_level <= 10)', name=op.f('health_daily_track_stress_level_check')),
    sa.ForeignKeyConstraint(['patient_id'], ['memotion.users.user_id'], name=op.f('fk_health_track_patient'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('track_id', name=op.f('health_daily_track_pkey')),
    sa.UniqueConstraint('patient_id', 'track_date', name=op.f('health_daily_track_patient_id_track_date_key')),
    schema='memotion'
    )
    op.create_table('task_reminder',
    sa.Column('reminder_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('task_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('remind_before', postgresql.INTERVAL(), autoincrement=False, nullable=False),
    sa.Column('remind_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('channel', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'SCHEDULED'::character varying"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.CheckConstraint("(channel)::text = ANY ((ARRAY['APP_NOTIFICATION'::character varying, 'SMS'::character varying, 'VOICE_CALL'::character varying])::text[])", name=op.f('task_reminder_channel_check')),
    sa.CheckConstraint("(status)::text = ANY ((ARRAY['SCHEDULED'::character varying, 'SENT'::character varying, 'CANCELLED'::character varying])::text[])", name=op.f('task_reminder_status_check')),
    sa.ForeignKeyConstraint(['task_id'], ['memotion.task.task_id'], name=op.f('fk_reminder_task'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('reminder_id', name=op.f('task_reminder_pkey')),
    schema='memotion'
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_login', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('user_pkey')),
    schema='memotion'
    )
    op.create_index(op.f('ix_memotion_user_full_name'), 'user', ['full_name'], unique=False, schema='memotion')
    op.create_index(op.f('ix_memotion_user_email'), 'user', ['email'], unique=True, schema='memotion')
    # ### end Alembic commands ###
